server:
    port: 9000  # 9000번 포트로 실행

spring:
    application:
        name: demo

    datasource:
        platform: mysql
        url: jdbc:mysql://bon-db.cntk1o6zakn2.ap-northeast-2.rds.amazonaws.com/bonDB?autoReconnect=true
        # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
        username: master # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
        password: Bon0206! # 비밀번호를 입력해주세요!
        driver-class-name: com.mysql.cj.jdbc.Driver


# 문자 서비스는 과금되므로 신중한 사용 부탁드립니다!
url:
    base: http://127.0.0.1:9000

ncp:
    access_key: bz0iE75n00Gnhm47frJq
    service_id: ncp:sms:kr:282129099849:rising_market
    secret_key: SenOzPhEC0ZhSxxQkga1bnn9F3wTTgcznZXCgHOt

social:
    naver:
        client-id: gMbJWRpKYUPAVDX9jWep
        client-secret: jJEoGPQ3H4
        redirect: /naver-accounts/redirect
        authorization-grant-type: authorization_code
        scope: name, email, profile_image
        client-name: Naver
        url:
            login: https://nid.naver.com/oauth2.0/authorize
            token: https://nid.naver.com/oauth2.0/token
            profile: https://openapi.naver.com/v1/nid/me
    google:
        client-id: 738547209082-qfmq78h75c33esbd8r0b7stqq5b127ua.apps.googleusercontent.com
        client-secret: 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
        redirect: /google-accounts/redirect
        scope: profile,email,openid
        url:
            login: https://accounts.google.com
            auth: https://oauth2.googleapis.com
    line:
        client-id: 1657006913
        client-secret: 1ca334f50d81b10d1dcaf603b4348a18
        redirect: /line-accounts/redirect
        url:
            login: https://access.line.me/oauth2/v2.1/authorize
            token: https://api.line.me/oauth2/v2.1/token
            profile: https://api.line.me/oauth2/v2.1/verify
